#! /bin/sh
# See documentation and license in README.md

if [[ $1 == "--toggle" ]]; then
	shift
	toggle=1
else
	toggle=0
fi

command="$*"
# zenity --info --text "$command"; # useful for debug

runningInstancesOfExec=$(ps -a -x -o command | grep -v grep | grep -v defunct | grep -v marathon | grep -c $command);

if [ $runningInstancesOfExec -gt 0 ]; then
	if [[ $toggle == "1" ]]; then
		# Determine active windowID, from https://github.com/dmikalova/brocket
		# and http://superuser.com/questions/382616/detecting-currently-active-window
		currentWindow="$(printf '0x%08x\n' $(xprop -root |
						 grep "_NET_ACTIVE_WINDOW(WINDOW)" |
						 grep -E -o 0x[0-9a-f]+))"

		currentWindowIsCommand="$(wmctrl -lx |
								  grep $currentWindow |
			 					  grep -ci "^0x[0-9a-f]*\s*[0-9]\s*[^ ]*$command")"
		if [ $currentWindowIsCommand -gt 0 ]; then
			exec xdotool windowminimize $currentWindow
		else
			exec wmctrl -x -a $command;
		fi
	else
		exec wmctrl -x -a $command;
	fi
else
	exec $command;
fi

